version: '3.5'
services:
  nginx: 
    image: nginx:latest
    container_name: cnt_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
      - 8443:443
      - 8081:8081
    networks:
      - redproxy

  app1:
    build: .
    container_name: cnt_web01
    expose:
      - "80"
    networks: 
     - redproxy

  app2:
    image: httpd
    container_name: cnt_web02
    expose:
      - "80"
    networks:
      - redproxy
networks:
  redproxy:
    name: redproxy
