version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: proxyw
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
      - 8443:443
      - 8081:8081
    networks:
      - redproxy

  web:
    image: httpd
    container_name: production
    expose:
      - "80"
    networks: 
     - redproxy

networks:
  redproxy:
