version: '3.5'

services:
   wordpress:
     container_name: cnt_wdp
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - sgf:/var/www/html
     ports:
       - "8089:80"
     networks:
       - inet
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: password

   db:
     container_name: cnt_wdpdb
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: password
     networks:
       - inet 
     volumes:
       - sg_data:/var/lib/mysql:rw

volumes:
    sgf:
     name: sgf       
    sg_data:
     name: sg_data

networks:
    inet:
     name: inet      
